### PR TITLE
update plugin to support new converter instead of old data-converter

### PR DESCRIPTION
**Pull request by dmytrolev**

### CODE REVIEW

**Comment by doowb** [comment]
Thanks! Will you change the package.json version back?

I'll get it merged in after that, thanks.

**Comment by dimalev** [comment]
done

can you please refer me to some package version related documentation ? i thought this update and new dependencies can affect users' environment.

**Comment by doowb** [comment]
> i thought this update and new dependencies can affect users' environment.

You're correct. I wanted to make sure to keep your other changes with your name and handle the versioning before publishing to npm. I'll probably bump the minor since a different library is being used, but I'll be updating a few other things too.

**Comment by dimalev** [comment]
k, kool :)

**Pull request merged**
